# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7e2747b29cf4ad1448184d521c2f67589ebd115d5a0f5a4c4328201585449de2509da9a02b864bfc4e021aff761c10293dc1830301d2d9bc6373dcdb94e315

test:
  secret_key_base: 2b96065e95b501ea42c57db1c1d330d9a164b9f8726370438a178d50d538dd14f5fa48f63489194359bb0af82c59f156d8d17251d93f6fc585c2030a641932ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
